# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
