# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20170611_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
    ]
