# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_remove_category_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='categories',
            field=models.ManyToManyField(default=None, to='restaurants.Category'),
        ),
    ]
