# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_auto_20170704_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
