# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id_purchaser',
            new_name='is_purchaser',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='site',
            field=models.CharField(default='', max_length=100),
        ),
    ]
