# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userprofile_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_purchaser',
            field=models.BooleanField(default=False),
        ),
    ]
