# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_userprofile_is_purchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='collect_place',
            field=models.CharField(blank=True, max_length=50, verbose_name='Miejsce odbioru'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchaser_message',
            field=models.CharField(blank=True, max_length=400, verbose_name='Informacja od zamawiającego'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Zamawiający'),
        ),
    ]
