# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20170616_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purchaser_name',
            field=models.CharField(blank=True, max_length=400, verbose_name='Zamawiający - nazwa'),
        ),
    ]
