# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20170616_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, max_length=400, verbose_name='Metoda płatności'),
        ),
    ]
