# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userprofile_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('import_menu', 'Import menu'),)},
        ),
    ]
