# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('order_status', models.CharField(choices=[('NEW', 'Nowe'), ('SENT', 'Wysłane'), ('ACCEPTED', 'Przyjęte')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_deadline', models.TimeField()),
                ('order_date', models.DateField()),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Restaurant')),
                ('active', models.BooleanField(default=False, verbose_name='Aktywny')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderSettings'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
