# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cena zamówienia bez dostawy', max_digits=10, verbose_name='Cena'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Data zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Nazwa dania'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('SENT', 'Wysłane'), ('ACCEPTED', 'Przyjęte')], default='NEW', max_length=10, verbose_name='Status zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Zapłacono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena z dostawą'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Zamawiający'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_deadline',
            field=models.TimeField(verbose_name='Zamówienia można składać do'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='purchaser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchaser', to=settings.AUTH_USER_MODEL, verbose_name='Kupujący'),
        ),
    ]
