# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170528_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettings',
            name='order_deadline',
            field=models.TimeField(verbose_name='Termin składania zamówień'),
        ),
    ]
