# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:59
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20170531_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettings',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_deadline',
            field=models.TimeField(default=datetime.datetime(2017, 6, 1, 10, 30), verbose_name='Termin składania zamówień'),
        ),
    ]
