# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20170601_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettings',
            name='order_deadline',
            field=models.TimeField(default='10:30', verbose_name='Termin składania zamówień'),
        ),
    ]
