# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 19:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170601_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cena zamówienia bez dostawy'),
        ),
        migrations.AlterField(
            model_name='ordersettings',
            name='order_date',
            field=models.DateField(),
        ),
    ]
