# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20170608_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('ACCEPTED', 'Przyjęte'), ('ORDERED', 'Zamówione'), ('COMPLETED', 'Do odbioru')], default='NEW', max_length=10, verbose_name='Status zamówienia'),
        ),
    ]
