# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 18:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_auto_20170612_2045'),
        ('orders', '0014_auto_20170611_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.Dish'),
        ),
    ]
