# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20170612_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.ManyToManyField(default=None, to='restaurants.Dish', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('ACCEPTED', 'Zamówione'), ('COMPLETED', 'Do odbioru')], default='NEW', max_length=10, verbose_name='Status zamówienia'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena zamówienia'),
        ),
    ]
