# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20170613_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersettings',
            name='order_date',
            field=models.DateField(),
        ),
    ]
