# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 17:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20170613_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderSettings', verbose_name='Ustawienia'),
        ),
    ]
