# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20170619_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=4000, verbose_name='Komentarz'),
        ),
    ]
