# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersettings',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktywny'),
        ),
    ]
