# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 16:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0027_auto_20170701_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='purchaser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_purchaser', to=settings.AUTH_USER_MODEL, verbose_name='Kupujący'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Zamawiający'),
        ),
    ]
